import { 
  Droplets, 
  Sun, 
  Activity, 
  Snowflake, 
  Pill, 
  Coffee, 
  Moon, 
  Footprints, 
  Brain, 
  Dumbbell, 
  Apple, 
  Timer, 
  AlarmClock, 
  Zap, 
  Heart, 
  Wind,
  Bell,
  Check,
  Plus,
  X,
  Trash2,
  Edit2,
  Settings,
  Repeat,
  Info,
  LayoutGrid,
  ShoppingCart,
  Flame,
  GlassWater,
  Leaf,
  Stethoscope,
  Thermometer,
  Trees,
  Waves,
  Wifi,
  WifiOff,
  Battery,
  BatteryCharging,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Shield,
  ShieldCheck,
  Star,
  Trophy,
  Target,
  Award,
  Medal,
  Flag,
  Map,
  MapPin,
  Navigation,
  Compass,
  Clock,
  Calendar,
  Watch,
  Smartphone,
  Tablet,
  Laptop,
  Monitor,
  Tv,
  Speaker,
  Mic,
  Headphones,
  Music,
  Video,
  Camera,
  Image,
  File,
  FileText,
  Folder,
  Search,
  Menu,
  MoreHorizontal,
  MoreVertical,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ExternalLink,
  Share,
  Download,
  Upload,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Play,
  Pause,
  Square,
  SkipBack,
  SkipForward,
  FastForward,
  Rewind,
  Volume2,
  VolumeX,
  Mail,
  Send,
  MessageSquare,
  Phone,
  User,
  Users,
  UserPlus,
  UserMinus,
  LogIn,
  LogOut,
  Key,
  Home,
  Cloud,
  CloudRain,
  CloudLightning,
  CloudSnow,
  CloudSun,
  CloudMoon,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  Umbrella,
  Wind as WindIcon,
  Sun as SunIcon,
  Moon as MoonIcon,
  Zap as ZapIcon,
  Flame as FlameIcon,
  Droplets as DropletsIcon,
  Activity as ActivityIcon,
  Heart as HeartIcon,
  Brain as BrainIcon,
  Dumbbell as DumbbellIcon,
  Apple as AppleIcon,
  Timer as TimerIcon,
  AlarmClock as AlarmClockIcon,
  Pill as PillIcon,
  Coffee as CoffeeIcon,
  Footprints as FootprintsIcon,
  Snowflake as SnowflakeIcon,
  Bell as BellIcon,
  Check as CheckIcon,
  Plus as PlusIcon,
  X as XIcon,
  Trash2 as Trash2Icon,
  Edit2 as Edit2Icon,
  Settings as SettingsIcon,
  Repeat as RepeatIcon,
  Info as InfoIcon,
  LayoutGrid as LayoutGridIcon,
  ShoppingCart as ShoppingCartIcon,
  GlassWater as GlassWaterIcon,
  Leaf as LeafIcon,
  Stethoscope as StethoscopeIcon,
  Thermometer as ThermometerIcon,
  Trees as TreesIcon,
  Waves as WavesIcon,
  Wifi as WifiIcon,
  WifiOff as WifiOffIcon,
  Battery as BatteryIcon,
  BatteryCharging as BatteryChargingIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  Lock as LockIcon,
  Unlock as UnlockIcon,
  Shield as ShieldIcon,
  ShieldCheck as ShieldCheckIcon,
  Star as StarIcon,
  Trophy as TrophyIcon,
  Target as TargetIcon,
  Award as AwardIcon,
  Medal as MedalIcon,
  Flag as FlagIcon,
  Map as MapIcon,
  MapPin as MapPinIcon,
  Navigation as NavigationIcon,
  Compass as CompassIcon,
  Clock as ClockIcon,
  Calendar as CalendarIcon,
  Watch as WatchIcon,
  Smartphone as SmartphoneIcon,
  Tablet as TabletIcon,
  Laptop as LaptopIcon,
  Monitor as MonitorIcon,
  Tv as TvIcon,
  Speaker as SpeakerIcon,
  Mic as MicIcon,
  Headphones as HeadphonesIcon,
  Music as MusicIcon,
  Video as VideoIcon,
  Camera as CameraIcon,
  ImageIcon as ImageIconIcon,
  File as FileIcon,
  FileText as FileTextIcon,
  Folder as FolderIcon,
  Search as SearchIcon,
  Menu as MenuIcon,
  MoreHorizontal as MoreHorizontalIcon,
  MoreVertical as MoreVerticalIcon,
  ArrowUp as ArrowUpIcon,
  ArrowDown as ArrowDownIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  ChevronUp as ChevronUpIcon,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ExternalLink as ExternalLinkIcon,
  Share as ShareIcon,
  Download as DownloadIcon,
  Upload as UploadIcon,
  RefreshCw as RefreshCwIcon,
  RotateCcw as RotateCcwIcon,
  RotateCw as RotateCwIcon,
  Play as PlayIcon,
  Pause as PauseIcon,
  Square as SquareIcon,
  SkipBack as SkipBackIcon,
  SkipForward as SkipForwardIcon,
  FastForward as FastForwardIcon,
  Rewind as RewindIcon,
  Volume2 as Volume2Icon,
  VolumeX as VolumeXIcon,
  Mail as MailIcon,
  Send as SendIcon,
  MessageSquare as MessageSquareIcon,
  Phone as PhoneIcon,
  User as UserIcon,
  Users as UsersIcon,
  UserPlus as UserPlusIcon,
  UserMinus as UserMinusIcon,
  LogIn as LogInIcon,
  LogOut as LogOutIcon,
  Key as KeyIcon,
  Home as HomeIcon,
  Cloud as CloudIcon,
  CloudRain as CloudRainIcon,
  CloudLightning as CloudLightningIcon,
  CloudSnow as CloudSnowIcon,
  CloudSun as CloudSunIcon,
  CloudMoon as CloudMoonIcon,
  CloudDrizzle as CloudDrizzleIcon,
  CloudFog as CloudFogIcon,
  CloudHail as CloudHailIcon,
  Umbrella as UmbrellaIcon
} from 'lucide-react';

export const ICON_MAP: Record<string, any> = {
  Droplets,
  Sun,
  Activity,
  Snowflake,
  Pill,
  Coffee,
  Moon,
  Footprints,
  Brain,
  Dumbbell,
  Apple,
  Timer,
  AlarmClock,
  Zap,
  Heart,
  Wind,
  Bell,
  Check,
  Plus,
  X,
  Trash2,
  Edit2,
  Settings,
  Repeat,
  Info,
  LayoutGrid,
  ShoppingCart,
  Flame,
  GlassWater,
  Leaf,
  Stethoscope,
  Thermometer,
  Trees,
  Waves,
  Wifi,
  WifiOff,
  Battery,
  BatteryCharging,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Shield,
  ShieldCheck,
  Star,
  Trophy,
  Target,
  Award,
  Medal,
  Flag,
  Map,
  MapPin,
  Navigation,
  Compass,
  Clock,
  Calendar,
  Watch,
  Smartphone,
  Tablet,
  Laptop,
  Monitor,
  Tv,
  Speaker,
  Mic,
  Headphones,
  Music,
  Video,
  Camera,
  Image,
  File,
  FileText,
  Folder,
  Search,
  Menu,
  MoreHorizontal,
  MoreVertical,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ExternalLink,
  Share,
  Download,
  Upload,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Play,
  Pause,
  Square,
  SkipBack,
  SkipForward,
  FastForward,
  Rewind,
  Volume2,
  VolumeX,
  Mail,
  Send,
  MessageSquare,
  Phone,
  User,
  Users,
  UserPlus,
  UserMinus,
  LogIn,
  LogOut,
  Key,
  Home,
  Cloud,
  CloudRain,
  CloudLightning,
  CloudSnow,
  CloudSun,
  CloudMoon,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  Umbrella
};

export const SELECTABLE_ICONS = [
  'Activity', 'Droplets', 'Sun', 'Moon', 'Coffee', 'Footprints', 'Pill', 'Snowflake',
  'Brain', 'Dumbbell', 'Apple', 'Timer', 'AlarmClock', 'Zap', 'Heart', 'Wind',
  'Flame', 'GlassWater', 'Leaf', 'Stethoscope', 'Thermometer', 'Trees', 'Waves',
  'Bell', 'Check', 'Star', 'Trophy', 'Target', 'Award', 'Medal', 'Flag',
  'Clock', 'Calendar', 'Watch', 'Smartphone', 'Laptop', 'Headphones', 'Music',
  'Video', 'Camera', 'Image', 'FileText', 'Search', 'User', 'Users', 'Home',
  'Cloud', 'CloudRain', 'CloudLightning', 'Umbrella'
];
